# Generated by Django 5.2.14 on 2026-09-07 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('delivery', '0001_initial'),
        ('inventory', '0004_stockreservation_sales_order'),
        ('sales_order', '0002_salesorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='delivery.delivery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='inventory.product')),
                ('sales_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='sales_order.salesorderitem')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='delivery_item_quantity_positive'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='delivery_item_unit_price_non_negative'), models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='delivery_item_amount_non_negative')],
            },
        ),
    ]
