# Generated by Django 5.2.14 on 2026-08-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, choices=[('ACCOUNTS_RECEIVABLE', 'Accounts Receivable'), ('SALES_REVENUE', 'Sales Revenue')], max_length=30, null=True),
        ),
    ]
