# Generated by Django 5.2.14 on 2026-08-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='resolution_note',
            field=models.TextField(blank=True),
        ),
    ]
