# Generated by Django 5.2.14 on 2026-08-13 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_support', '0002_case_resolution_note'),
        ('company', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('STATUS_CHANGED', 'Status Changed'), ('COMMENTED', 'Commented'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=30)),
                ('message', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='case_support.case')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_activities', to='employee.employee')),
            ],
            options={
                'db_table': 'case_activities',
            },
        ),
    ]
