# Generated by Django 5.2.14 on 2026-08-13 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_support', '0003_caseactivity'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_due_at', models.DateTimeField()),
                ('resolution_due_at', models.DateTimeField()),
                ('response_breached', models.BooleanField(default=False)),
                ('resolution_breached', models.BooleanField(default=False)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sla', to='case_support.case')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
            ],
            options={
                'db_table': 'case_slas',
            },
        ),
    ]
