# Generated by Django 5.2.14 on 2026-08-10 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64)),
                ('prefix', models.CharField(blank=True, max_length=8)),
                ('last_number', models.BigIntegerField(default=0)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
            ],
            options={
                'db_table': 'sequences',
                'constraints': [models.UniqueConstraint(fields=('company', 'key'), name='uq_seq_key_per_company')],
            },
        ),
    ]
