# Generated by Django 5.2.14 on 2026-08-13 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('inventory', '0004_stockreservation_sales_order'),
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='inventory.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='purchase_order.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_order_items',
            },
        ),
    ]
