# Generated by Django 5.2.14 on 2026-08-20 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('employee', '0001_initial'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_requests', to='travel.destination')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_requests', to='employee.employee')),
            ],
            options={
                'db_table': 'travel_request',
            },
        ),
    ]
