# Generated by Django 5.2.14 on 2026-08-20 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('employee', '0001_initial'),
        ('travel', '0002_travelrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRequestApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_request_approvals', to='employee.employee')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='travel.travelrequest')),
            ],
            options={
                'db_table': 'travel_request_approval',
                'constraints': [models.UniqueConstraint(fields=('company', 'travel_request', 'approved_by'), name='uq_travel_request_approval')],
            },
        ),
    ]
