# Generated by Django 5.2.14 on 2026-08-21 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('employee', '0001_initial'),
        ('travel', '0003_travelrequestapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRequestRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('rejected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_request_rejections', to='employee.employee')),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rejections', to='travel.travelrequest')),
            ],
            options={
                'db_table': 'travel_request_rejection',
            },
        ),
    ]
