# Generated by Django 5.2.14 on 2026-09-03 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='currency_records', to='company.company')),
            ],
            options={
                'db_table': 'currencies',
                'indexes': [models.Index(fields=['company', 'code'], name='currency_company_code_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='unique_currency_code_per_company')],
            },
        ),
    ]
