# Generated by Django 5.2.14 on 2026-09-03 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('default', models.BooleanField(default=False)),
                ('is_nbc', models.BooleanField(default=False)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
            ],
            options={
                'db_table': 'rate_categories',
                'indexes': [models.Index(fields=['company', 'code'], name='rate_category_company_code_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='unique_rate_category_code_per_company'), models.UniqueConstraint(condition=models.Q(('default', True)), fields=('company',), name='unique_default_rate_category_per_company')],
            },
        ),
    ]
