# Generated by Django 5.2.14 on 2026-09-03 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('currency', '0002_ratecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates', to='currency.currency')),
            ],
            options={
                'db_table': 'exchange_rates',
                'indexes': [models.Index(fields=['company', 'to_currency'], name='exrate_company_curr_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'to_currency'), name='unique_exchange_rate_currency_per_company')],
            },
        ),
    ]
