# Generated by Django 5.2.14 on 2026-09-03 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('currency', '0003_exchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=14, max_digits=30)),
                ('multi_or_divide', models.CharField(choices=[('multi', 'Multiply'), ('divide', 'Divide')], default='multi', max_length=10)),
                ('rate_value', models.DecimalField(decimal_places=20, max_digits=40)),
                ('rate_reciprocal', models.DecimalField(decimal_places=32, max_digits=50)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('exchange_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='currency.exchangerate')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rate_details', to='currency.currency')),
                ('rate_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rate_details', to='currency.ratecategory')),
            ],
            options={
                'db_table': 'exchange_rate_details',
                'indexes': [models.Index(fields=['from_currency', 'effective_date'], name='exrate_detail_from_date_idx'), models.Index(fields=['effective_date', 'rate_category'], name='exrate_detail_date_cat_idx')],
                'constraints': [models.UniqueConstraint(fields=('exchange_rate', 'from_currency', 'effective_date', 'rate_category'), name='unique_exchange_rate_detail')],
            },
        ),
    ]
