# Generated by Django 5.2.16 on 2026-08-05 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('company', '0001_initial'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='account.account')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='journal.journalentry')),
                ('journal_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='journal.journalentryline')),
            ],
            options={
                'db_table': 'ledger_entry',
            },
        ),
    ]
