# Generated by Django 5.2.14 on 2026-08-11 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=128)),
                ('stock_quantity', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
            ],
            options={
                'db_table': 'products',
                'constraints': [models.UniqueConstraint(fields=('company', 'sku'), name='uq_sku_per_company'), models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='ck_product_stock_non_negative')],
            },
        ),
    ]
