# Generated by Django 5.2.14 on 2026-08-12 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('employee', '0001_initial'),
        ('inventory', '0002_stockreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('DAMAGE', 'Damage'), ('ADJUSTMENT_IN', 'Adjustment_in'), ('ADJUSTMENT_OUT', 'Adjustment_out'), ('INITIAL', 'Initial')], max_length=20)),
                ('quantity', models.BigIntegerField()),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('note', models.TextField(blank=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='employee.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.product')),
            ],
            options={
                'db_table': 'stock_movements',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_stock_movement_quantity_positive')],
            },
        ),
    ]
