# Generated by Django 5.2.14 on 2026-08-12 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement'),
        ('sales_order', '0002_salesorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreservation',
            name='sales_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='sales_order.salesorder'),
            preserve_default=False,
        ),
    ]
