# Generated by Django 5.2.14 on 2026-09-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='reimbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
