# Generated by Django 5.2.14 on 2026-09-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_expense_reimbursed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('TRANSPORTATION', 'Transportation'), ('MEALS', 'Meals'), ('HOTEL', 'Hotel'), ('OFFICE', 'Office'), ('COMMUNICATION', 'Communication'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
