# Generated by Django 5.2.14 on 2026-08-06 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='company.company')),
            ],
            options={
                'db_table': 'roles',
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='uq_company_roles_code'), models.UniqueConstraint(fields=('company', 'name'), name='uq_company_roles_name')],
            },
        ),
    ]
