# Generated by Django 5.2.14 on 2026-09-09 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('employee', '0002_employee_work_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Contract'), ('ID_DOCUMENT', 'ID Document'), ('RESUME', 'Resume'), ('CERTIFICATE', 'Certificate'), ('TAX_DOCUMENT', 'Tax Document'), ('OTHER', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='employee_documents/')),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='employee.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
