# Generated by Django 5.2.14 on 2026-09-09 04:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('employee', '0002_employee_work_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='employee.employee')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('company', 'employee', 'year', 'month'), name='unique_payroll_per_employee_month')],
            },
        ),
    ]
