# Generated by Django 5.2.14 on 2026-08-13 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('employee', '0001_initial'),
        ('inventory', '0004_stockreservation_sales_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='employee.employee')),
            ],
            options={
                'db_table': 'purchase_requests',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estimated_subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_items', to='inventory.product')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='purchase_request.purchaserequest')),
            ],
            options={
                'db_table': 'purchase_request_items',
            },
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.UniqueConstraint(fields=('company', 'request_number'), name='uq_purchase_request_number_per_company'),
        ),
    ]
