# Generated by Django 5.2.14 on 2026-08-13 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('purchase_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_purchase_requests', to='employee.employee'),
        ),
    ]
