# Generated by Django 5.2.14 on 2026-08-13 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('purchase_request', '0002_purchaserequest_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_purchase_requests', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='rejected_reason',
            field=models.TextField(blank=True),
        ),
    ]
