# Generated by Django 5.2.14 on 2026-08-10 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_role'),
        ('accounts_receivable', '0003_salesinvoice_journal_alter_salesinvoice_status'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('remarks', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_payments', to='account.account')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts_receivable.salesinvoice')),
            ],
            options={
                'db_table': 'sales_invoice_payments',
            },
        ),
    ]
