# Generated by Django 5.2.14 on 2026-08-10 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_receivable', '0004_salesinvoicepayment'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoicepayment',
            name='journal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_payment', to='journal.journalentry'),
        ),
    ]
