# Generated by Django 5.2.14 on 2026-09-07 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_receivable', '0005_salesinvoicepayment_journal'),
        ('delivery', '0002_deliveryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='delivery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='delivery.delivery'),
        ),
    ]
