# Generated by Django 5.2.14 on 2026-08-26 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('transport', '0003_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_type', models.CharField(choices=[('FUEL', 'Fuel'), ('TOLL', 'Toll'), ('PARKING', 'Parking'), ('MAINTENANCE', 'Maintenance'), ('DRIVER_ALLOWANCE', 'Driver Allowance'), ('OTHER', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expense_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense', to='transport.transport')),
            ],
            options={
                'db_table': 'transport_expense',
            },
        ),
    ]
