# Generated by Django 5.2.14 on 2026-08-26 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('employee', '0001_initial'),
        ('transport', '0004_transportexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boarded_at', models.DateTimeField(blank=True, null=True)),
                ('dropped_off_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_passenger_records', to='employee.employee')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_records', to='transport.transport')),
            ],
            options={
                'db_table': 'transport_passenger',
            },
        ),
        migrations.AddField(
            model_name='transport',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='passenger_transports', through='transport.TransportPassenger', to='employee.employee'),
        ),
        migrations.AddConstraint(
            model_name='transportpassenger',
            constraint=models.UniqueConstraint(fields=('transport', 'employee'), name='unique_transport_passenger'),
        ),
    ]
